# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-03 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category_ar',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='post',
            name='category_fr',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
